In [1]:
import torch

In [2]:
x = torch.rand(4,3)

In [3]:
x

tensor([[0.8331, 0.3989, 0.1726],
        [0.8553, 0.5025, 0.5448],
        [0.7945, 0.4921, 0.7868],
        [0.7891, 0.9524, 0.2160]])

In [6]:
x.size()

torch.Size([4, 3])

In [7]:
x.shape

torch.Size([4, 3])

In [8]:
x.dtype

torch.float32

In [9]:
x.type

<function Tensor.type>

In [10]:
y = torch.rand(4,3)

In [11]:
y

tensor([[0.3124, 0.2334, 0.8765],
        [0.9439, 0.2184, 0.2237],
        [0.2252, 0.1424, 0.6169],
        [0.9033, 0.3496, 0.6783]])

In [12]:
x+y

tensor([[1.1454, 0.6322, 1.0492],
        [1.7992, 0.7208, 0.7685],
        [1.0197, 0.6344, 1.4037],
        [1.6925, 1.3020, 0.8943]])

In [13]:
?torch.rand

Docstring:
rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with random numbers from a uniform distribution
on the interval :math:`[0, 1)`

The shape of the tensor is defined by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type


In [14]:
z = torch.randn(4,3)

In [15]:
z

tensor([[-2.9654,  0.8313, -0.6882],
        [ 0.0100, -0.6879, -1.3661],
        [-0.3898, -0.2109, -1.2044],
        [ 0.0753, -0.2092, -0.0124]])

In [16]:
x = torch.randn(1)

In [17]:
x

tensor([2.1413])

In [18]:
x.item_()

AttributeError: 'Tensor' object has no attribute 'item_'

In [19]:
scalar = x.item()

In [20]:
scalar

2.1413371562957764

In [22]:
type(scalar)

float

In [23]:
type(x)

torch.Tensor

In [24]:
a = torch.ones(5)

In [25]:
a

tensor([1., 1., 1., 1., 1.])

In [27]:
b = a.numpy()

In [28]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [29]:
b[2] = 5

In [30]:
b

array([1., 1., 5., 1., 1.], dtype=float32)

In [31]:
a

tensor([1., 1., 5., 1., 1.])

In [32]:
x = torch.ones(2,2, requires_grad=True)

In [36]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [37]:
z = y * y * 3
out = z.mean()

In [38]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [41]:
y @ y

tensor([[18., 18.],
        [18., 18.]], grad_fn=<MmBackward>)

In [43]:
out.backward()

In [44]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [45]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  27.9797, 1780.7260, -561.2035], grad_fn=<MulBackward0>)


In [48]:
x = torch.zeros(2, requires_grad=True)

In [49]:
x

tensor([0., 0.], requires_grad=True)

In [56]:
y[0] = (14 * x[0]**2) + x[1]

In [57]:
y[1] = (6 * x[0]**3) + (20 * x[1]**3)

In [55]:
y = torch.zeros(2)

In [58]:
y

tensor([0., 0.], grad_fn=<CopySlices>)

In [59]:
print(y)

tensor([0., 0.], grad_fn=<CopySlices>)


In [61]:
v = torch.tensor([1 ,1], dtype=torch.float)

In [62]:
y.backward(v)

In [63]:
print(x.grad)

tensor([0., 1.])


In [64]:
x = torch.ones(3, requires_grad=True)

In [65]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-286.6894, 1092.4890,    2.5669], grad_fn=<MulBackward0>)


In [66]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [76]:
x = torch.ones(3, requires_grad=True)

In [77]:
x

tensor([1., 1., 1.], requires_grad=True)

In [79]:
y = x ** 3

In [81]:
y = 2 * y

In [84]:
y.backward(torch.tensor([1,1,1], dtype=torch.float))

In [85]:
print(x.grad)

tensor([6., 6., 6.])


In [75]:
y = x^3

RuntimeError: bitwise_xor(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.